version: "3.7"

services:
    app:
        user: ${DOCKER_USER:-1000}:${DOCKER_UID:-1001}
        build:
            args:
                user: ${DOCKER_USER:-1000}
                uid: ${DOCKER_UID:-1001}
            context: ./
            dockerfile: .docker/Dockerfile
        environment:
            PHP_IDE_CONFIG: 'serverName=neuffer.loc'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        image: ${DOCKER_IMAGE_NAME:-neuffer}-app-image
        container_name: ${DOCKER_IMAGE_NAME:-neuffer}-app-container
        restart: 'no'
        working_dir: /var/www
        tty: true
        volumes:
            - ./:/var/www
    composer:
        user: ${DOCKER_USER:-1000}:${DOCKER_UID:-1001}
        image: composer:2.4.4
        restart: 'no'
        working_dir: /var/www
        tty: true
        volumes:
            - ./:/var/www
